timezone: America/Denver
author: Andrew Schwartz
title: Java Projects

description: > # this means to ignore newlines until "baseurl:"
  A community created list of projects to improve your Java skills.
exclude:
  - Gemfile
  - Gemfile.lock
