timezone: America/Denver
author: Andrew Schwartz
title: Java Projects

description: > # this means to ignore newlines until "baseurl:"
  A community directory of projects to learn and improve Java skills
exclude:
  - Gemfile
  - Gemfile.lock
